# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

steps:
  # compute build version
  - task: PowerShell@2
    condition: succeeded()
    displayName: Compute build version
    inputs:
      targetType: 'inline'
      script: |
        $counter = $env:REVISION
        $version = [int]$counter

        $VersionMajor = "1"
        $VersionMinor = "7"
        $BuildNumber = "0"
        
        $buildSimpleVersion = $VersionMajor + "." + $VersionMinor + "." + $BuildNumber
        $buildFullVersion = $buildSimpleVersion + "." + $version.ToString()

        Write-Host "$("##vso[task.setvariable variable=TARGET_BUILD_COUNTER]")$version"

        Write-Host ">>$buildFullVersion<<"
        
        # need to hijack NBGV variables that are expected in the build CMake command and others that follow
        Write-Host "$("##vso[task.setvariable variable=NBGV_AssemblyVersion]")$buildFullVersion"
        Write-Host "$("##vso[task.setvariable variable=NBGV_Version]")$buildSimpleVersion"

        Write-Host "$("##vso[task.setvariable variable=NBGV_VersionMajor]")$VersionMajor"
        Write-Host "$("##vso[task.setvariable variable=NBGV_VersionMinor]")$VersionMinor"
        Write-Host "$("##vso[task.setvariable variable=NBGV_BuildNumber]")$BuildNumber"
    
        Write-Host "$("##vso[task.setvariable variable=NBGV_VersionHeight]")$version"
        Write-Host "$("##vso[task.setvariable variable=NBGV_SimpleVersion]")$buildSimpleVersion"
