sequenceDiagram
    activate PortCompositeDeviceManager
    Note over PortSerialManager: _threadWatch = new Thread(()
    loop TaskFactory[forEach TCP/IP, Serial]
    PortCompositeDeviceManager-->>PortSerialManager: StartDeviceWatchers
    end
    PortSerialManager-->>PortSerialManager : StartDeviceWatchersInternal
    alt is NotStarted
        PortSerialManager-->>DeviceWatcher : Start
    end
     alt is NotStarted
        DeviceWatcher-->>DeviceWatcher : Create Thread
    Note over DeviceWatcher: _threadWatch = new Thread(()
        DeviceWatcher-->>DeviceWatcher : StartWatcher
    Note over DeviceWatcher: _threadWatch.Start()
    end

