sequenceDiagram

participant CLRStartup
participant Debugger
participant Execution

    loop while(softReboot)
    
    CLRStartup-->>CLR_RT_Memory: Reset()


    CLRStartup-->>CLRStartup: Initialize(params)
     alt is success Initialize
        CLRStartup-->>CLRStartup: Load()
        alt is success Load
            CLRStartup-->>Execution : Execute()
            Execution-->>CLRStartup : result
        end
     end

     alt is RebootPending
        alt is Enter debug after exit
            CLRStartup-->>Debugger: Debugger_WaitForCommands()
            activate Debugger
            activate Execution
            Debugger-->>Debugger: Debugger_WaitForCommands()
            Debugger-->>Execution : DebuggerLoop
            deactivate Execution

        end
     end
     alt is RebootPending
        alt is ClrOnly
            Note over CLRStartup: softReboot = true
            Note over CLRStartup: set reboot Waiting for Debugger
            CLRStartup-->>CLRStartup : Cleanup()
            CLRStartup-->>targetHal : nanoHAL_Uninitialize
            CLRStartup-->>targetHal : nanoHAL_Initialize
        end
    end
end

