#
# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.
#

 SET( CMAKE_AR "C:/nftools/GNU_Tools_ARM_Embedded/13.2.rel1/bin/arm-none-eabi-ar.exe")
 SET( CMAKE_ASM_COMPILER "C:/nftools/GNU_Tools_ARM_Embedded/13.2.rel1/bin/arm-none-eabi-gcc.exe")
 SET( CMAKE_ASM_COMPILER_AR "C:/nftools/GNU_Tools_ARM_Embedded/13.2.rel1/bin/arm-none-eabi-gcc-ar.exe")
 SET( CMAKE_RANLIB "C:/nftools/GNU_Tools_ARM_Embedded/13.2.rel1/bin/arm-none-eabi-ranlib.exe")
 SET( CMAKE_CXX_COMPILER "C:/nftools/GNU_Tools_ARM_Embedded/13.2.rel1/bin/arm-none-eabi-g++.exe")
 SET( CMAKE_CXX_COMPILER_AR "C:/nftools/GNU_Tools_ARM_Embedded/13.2.rel1/bin/arm-none-eabi-gcc-ar.exe")
 SET( CMAKE_CXX_COMPILER_RANLIB "C:/nftools/GNU_Tools_ARM_Embedded/13.2.rel1/bin/arm-none-eabi-gcc-ranlib.exe")
 SET( CMAKE_C_COMPILER "C:/nftools/GNU_Tools_ARM_Embedded/13.2.rel1/bin/arm-none-eabi-gcc.exe")
 SET( CMAKE_C_COMPILER_AR "C:/nftools/GNU_Tools_ARM_Embedded/13.2.rel1/bin/arm-none-gcc-ar.exe")
 SET( CMAKE_C_COMPILER_RANLIB "C:/nftools/GNU_Tools_ARM_Embedded/13.2.rel1/bin/arm-none-eabi-gcc-ranlib.exe")
 SET( CMAKE_LINKER "C:/nftools/GNU_Tools_ARM_Embedded/13.2.rel1/bin/arm-none-eabi-ld.exe")
 SET( CMAKE_NM "C:/nftools/GNU_Tools_ARM_Embedded/13.2.rel1/bin/arm-none-eabi-nm.exe")
 SET( CMAKE_READELF "C:/nftools/GNU_Tools_ARM_Embedded/13.2.rel1/bin/arm-none-eabi-readelf.exe")
 SET( CMAKE_STRIP "C:/nftools/GNU_Tools_ARM_Embedded/13.2.rel1/bin/arm-none-eabi-strip.exe")
 SET( CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY")
 SET( CMAKE_OBJCOPY "C:/nftools/GNU_Tools_ARM_Embedded/13.2.rel1/bin/arm-none-eabi-objcopy.exe")
 SET( CMAKE_OBJDUMP "C:/nftools/GNU_Tools_ARM_Embedded/13.2.rel1/bin/arm-none-eabi-objdump.exe")
 SET( CMAKE_VERBOSE_MAKEFILE "1")
 SET( CMAKE_NM_UTIL "C:/nftools/GNU_Tools_ARM_Embedded/13.2.rel1/bin/arm-none-eabi-nm.exe")
 SET( CMAKE_SIZE_UTIL "C:/nftools/GNU_Tools_ARM_Embedded/13.2.rel1/bin/arm-none-eabi-size.exe"
